# Commented while we wait for the new Electron versions to ship

name: Cache

on:
  push:
    branches:
      - "master"

jobs:
  release:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true

    strategy:
      matrix:
        os: [macos-10.15, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Node.js, NPM and Yarn for Mac
        if: startsWith(matrix.os, 'macos')
        uses: actions/setup-node@v1
        with:
          node-version: 15

      - name: Install Node.js, NPM and Yarn for Windows
        if: startsWith(matrix.os, 'windows')
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - uses: actions/cache@v2.1.0
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Yarn
        run: |
          yarn install
          yarn clean
          yarn node-gyp clean
