name: Upload Sentry sourcemaps

on: push

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 10

      - name: Upload to Sentry
        run: "./sentry.sh"
        env:
          # macOS notarization API key
          SENTRY_ORG: soulmate
          SENTRY_PROJECT: ide
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
